name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: check
        run: uname -a && echo && free -h && echo && df -h && echo && lscpu

      - name: build
        run: chmod +x build.sh && ./build.sh

      - name: generate tag
        id: tag
        run: |
          echo "tag=build-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Build ${{ steps.tag.outputs.tag }}
          files: |
            out/BOOTX64.EFI
            out/BOOTX64.EFI.sha256
            out/BOOTX64.EFI.md5